# Generated by Django 4.2.4 on 2023-08-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutphoto', models.ImageField(upload_to='about/profile')),
                ('aboutdetail', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('work', models.CharField(max_length=150)),
                ('freelance', models.CharField(max_length=150)),
                ('freelance_num', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='first_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstimage', models.ImageField(upload_to='profile')),
                ('displayname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
